// 8.REACT/demo/src/Components/Footer/Login/Login.jsx
import React from 'react'

export default function Login() {
  return (
    <div>
      <div className="row">
        <div className="col-6">
          <img src="" alt="" />
        </div>
        <div className="col-6">

      <form>
        <div class="mb-3">
       <label for="exampleInputEmail1" class="form-label">Email address</label>
       <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"/>
      <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
     </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1"/>
  </div>
  <div class="mb-3 form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1"/>
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
 </form>
    </div>
    </div>
      
    </div>
  )
}

// 11.ANGULAR/my-app/src/app/login/login.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {
    msg:string ="Welcome to Login page"
    value:boolean=true;
    num:Number=343

    loginImg:string="https://img.freepik.com/free-vector/mobile-login-concept-illustration_114360-83.jpg?size=338&ext=jpg&ga=GA1.1.2113030492.1729209600&semt=ais_hybrid"

btnClick(){
  alert("Button clicked")
}

}

<div class="row">
    <div class="col-6">
        <img  width="100%" height="450px" [src]=loginImg alt="">
    </div>
    <div class="col-6">
        <form class="p-5 text-center m-5">
            <h1 class="m-3">Login Here....</h1>
            <!--string interpolation-->
            <p>{{msg}}</p>
            <div class="mb-2">
              <input placeholder="Email" type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
            </div>
            <div class="mb-2">
              <input placeholder="password" type="password" class="form-control" id="exampleInputPassword1">
            </div>
            <!--event binding-->
            <button  (click)="btnClick()"    routerLink="home" type="submit" class="btn btn-primary">Submit</button>
          </form>
    </div>
</div>
